name: MinecraftDashboard
main: de.gnmyt.mcdash.MinecraftDashboard
version: 1.1.5
api-version: 1.13
description: MCDash is a simple dashboard for your Minecraft server.
author: GNMYT
commands:
  panel:
    description: Changes the password of the current user
    aliases: [password, passwd]
    permission: mcdash.use