name: Build Minecraft Plugin

on:
  push:
    branches:
      - main  # Set this to your default branch
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'temurin'  # You can change this to match your preferred JDK distribution

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package -DskipTests  # Add other flags as needed

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: minecraft-plugin
        path: target/*.jar  # Adjust this path based on where your JAR file is placed after the build
